<%@ Page Title="ArticlesGrid" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ArticlesGrid.aspx.cs" Inherits="DrinkAndRate.Web.Admin.ArticlesGrid" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
	<h3 class="text-center alert alert-dismissable alert-success" id="headerInfo" runat="server">Articles Grid</h3>
	<div class="row">
		<div class="col-md-12">
			<asp:GridView CssClass="table table-striped table-hover table-bordered table-responsive"
				ID="gridView" runat="server" DataSourceID="EntityDataSourceProvider"
				AllowPaging="True" AllowSorting="True"
				AutoGenerateDeleteButton="true"
				AutoGenerateEditButton="true">
			</asp:GridView>
			<ef:EntityDataSource runat="server" ID="EntityDataSourceProvider"
				OnContextCreating="dataSource_ContextCreating"
				EntitySetName="Articles"
				EnableDelete="true" EnableInsert="true" EnableUpdate="true">
			</ef:EntityDataSource>
		</div>
	</div>
</asp:Content>