<%@ Page Title="ImagesGrid" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ImagesGrid.aspx.cs" Inherits="DrinkAndRate.Web.Admin.ImagesGrid" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
	<h3 class="text-center alert alert-dismissable alert-success" id="headerInfo" runat="server">Images Grid</h3>
	<div class="row">
		<div class="col-md-12">
			<asp:GridView CssClass="table table-striped table-hover table-bordered table-responsive"
				ID="gridView" runat="server" DataSourceID="EntityDataSourceProvider"
				AllowPaging="True" AllowSorting="True"
				AutoGenerateColumns="false"
				AutoGenerateDeleteButton="true"
				AutoGenerateEditButton="true">
				<Columns>
					<asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id"></asp:BoundField>
					<asp:BoundField DataField="Path" HeaderText="Path" ReadOnly="True" SortExpression="Path"></asp:BoundField>
					<asp:ImageField DataImageUrlField="Path" HeaderText="Image" ReadOnly="True"></asp:ImageField>
				</Columns>
			</asp:GridView>
			<ef:EntityDataSource runat="server" ID="EntityDataSourceProvider"
				OnContextCreating="dataSource_ContextCreating"
				EntitySetName="Images"
				EnableDelete="true" EnableInsert="true" EnableUpdate="true">
			</ef:EntityDataSource>
		</div>
	</div>
</asp:Content>